# Generated by Django 5.2.1 on 2025-05-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id_min', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProdMinero',
            fields=[
                ('id_productor_min', models.AutoField(primary_key=True, serialize=False)),
                ('nom_productor_min', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id_export', models.AutoField(primary_key=True, serialize=False)),
                ('Num_Exped1', models.CharField(max_length=100)),
                ('Num_Exped2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_export', models.DateField()),
                ('fecha_present_export', models.DateField()),
                ('pedido_comercial_export', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado_anulacion', models.BooleanField(default=False)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='app.pais')),
                ('id_productor_min', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='app.prodminero')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('id_min', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='app.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='MinExport',
            fields=[
                ('id_min_export', models.AutoField(primary_key=True, serialize=False)),
                ('Tn_min_export', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FOB_min_export', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_exports', to='app.exportacion')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_exports', to='app.tipo')),
            ],
        ),
    ]
