# Generated by Django 5.2.7 on 2025-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concesionario', models.CharField(max_length=255)),
                ('paga_canon', models.BooleanField()),
                ('mineral_explotacion', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('opcion_compra', models.BooleanField(default=False)),
                ('expediente', models.IntegerField(blank=True, null=True)),
                ('createby', models.TextField()),
                ('createdate', models.DateField()),
                ('updateby', models.TextField(blank=True, null=True)),
                ('updatedate', models.DateField(blank=True, null=True)),
                ('deleteby', models.TextField(blank=True, null=True)),
                ('deletedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simsaexpedientescontratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_expediente', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
