# Generated by Django 5.2.1 on 2025-05-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minexport',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='mineral',
            name='nom_min',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='minexport',
            name='id_min',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='min_exports', to='app.mineral'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mineral',
            name='id_min',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
