# Generated by Django 5.2.1 on 2025-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_minexport_id_tipo_mineral_nom_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='id_min',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
