# Generated by Django 5.2.1 on 2025-05-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mineral_id_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='coment_min',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='id_productor_min',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productor_min', to='app.prodminero'),
        ),
    ]
